package com.mycompany.manajemenkaryawan.db.frames.jabatan;

import com.mycompany.manajemenkaryawan.db.Basisdata;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class JabatanAddFrame extends javax.swing.JFrame {

    /**
     * Creates new form JabatanAddFrame
     */
    public JabatanAddFrame() {
        initComponents();
        ubahButton.setEnabled(false);
        try {
            Connection koneksi = Basisdata.getConnection();
            String findSQL = "SELECT id_karyawan FROM karyawan";
            Statement statement = koneksi.createStatement();
            ResultSet resultSet = statement.executeQuery(findSQL);
            while(resultSet.next()){
                idKaryawanComboBox.addItem(Integer.toString(resultSet.getInt("id_karyawan")));
            }
            koneksi.close();
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }
    public JabatanAddFrame(int id_karyawan, String jabatan) {
        initComponents();
        simpanButton.setEnabled(false);
    try {
    Connection koneksi = Basisdata.getConnection();
    String findSQL = "SELECT * FROM jabatan WHERE id_karyawan='" + id_karyawan + "' AND jabatan = '" + jabatan + "'";
    Statement statement = koneksi.createStatement();
    ResultSet resultSet = statement.executeQuery(findSQL);
    while(resultSet.next()){
        idKaryawanComboBox.addItem(Integer.toString(resultSet.getInt("id_karyawan")));
        jabatanTextField.setText(resultSet.getString("jabatan"));               
        dariTanggalDatePicker.setDate(resultSet.getDate("dari_tanggal"));
        sampaiTanggalDatePicker.setDate(resultSet.getDate("sampai_tanggal"));
    }
    koneksi.close();
} catch (SQLException ex) {
    System.err.println(ex.getMessage());
}
    }
//    public JabatanAddFrame() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jabatanTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dariTanggalDatePicker = new org.jdesktop.swingx.JXDatePicker();
        sampaiTanggalDatePicker = new org.jdesktop.swingx.JXDatePicker();
        idKaryawanComboBox = new javax.swing.JComboBox<>();
        ubahButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judulLabel.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(0, 153, 0));
        judulLabel.setText("Tambah Data Jabatan");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("ID Karyawan");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Jabatan");

        jabatanTextField.setBackground(new java.awt.Color(204, 255, 204));

        simpanButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        simpanButton.setForeground(new java.awt.Color(0, 153, 51));
        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        batalButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        batalButton.setForeground(new java.awt.Color(0, 153, 51));
        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Dari Tanggal");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Sampai Tanggal");

        dariTanggalDatePicker.setBackground(new java.awt.Color(204, 255, 204));

        sampaiTanggalDatePicker.setBackground(new java.awt.Color(204, 255, 204));

        idKaryawanComboBox.setBackground(new java.awt.Color(204, 255, 204));

        ubahButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ubahButton.setForeground(new java.awt.Color(0, 153, 51));
        ubahButton.setText("Ubah");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(batalButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(judulLabel)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jabatanTextField)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idKaryawanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(simpanButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ubahButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sampaiTanggalDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dariTanggalDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judulLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idKaryawanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jabatanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dariTanggalDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sampaiTanggalDatePicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ubahButton)
                            .addComponent(simpanButton))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batalButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        Date selectedDateDariTanggal = dariTanggalDatePicker.getDate();
    Date selectedDateSampaiTanggal = sampaiTanggalDatePicker.getDate();
    if (jabatanTextField.getText().equals("") || selectedDateDariTanggal == null || selectedDateSampaiTanggal == null) {
    JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
    return;
}
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String formattedDateDariTanggal = sdf.format(selectedDateDariTanggal);
    String formattedDateSampaiTanggal = sdf.format(selectedDateSampaiTanggal);
        
        try {
    Connection koneksi = Basisdata.getConnection();
    String id_karyawan = idKaryawanComboBox.getSelectedItem().toString();
    String jabatan = jabatanTextField.getText();

    String findSQL = "SELECT * FROM jabatan WHERE id_karyawan=?";
    PreparedStatement checkStatement = koneksi.prepareStatement(findSQL);
    checkStatement.setInt(1, Integer.parseInt(id_karyawan));
    ResultSet checkResult = checkStatement.executeQuery();

    if (checkResult.next()) {
        JOptionPane.showMessageDialog(null, "Data Sudah Ada");
    } else {
        String insertSQL = "INSERT INTO jabatan (id_karyawan, jabatan, dari_tanggal, sampai_tanggal) VALUES (?, ?, ?, ?)";
        PreparedStatement insertStatement = koneksi.prepareStatement(insertSQL);
        insertStatement.setInt(1, Integer.parseInt(id_karyawan));
        insertStatement.setString(2, jabatan);
        insertStatement.setString(3, formattedDateDariTanggal);
        insertStatement.setString(4, formattedDateSampaiTanggal);
        insertStatement.executeUpdate();
        koneksi.close();
    dispose();
    }


} catch (SQLException ex) {
    System.err.println(ex.getMessage());
}
        
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        dispose();
    }//GEN-LAST:event_batalButtonActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        
    Date selectedDateDariTanggal = dariTanggalDatePicker.getDate();
    Date selectedDateSampaiTanggal = sampaiTanggalDatePicker.getDate();
    if (jabatanTextField.getText().equals("") || selectedDateDariTanggal == null || selectedDateSampaiTanggal == null) {
    JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
    return;
}
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String formattedDateDariTanggal = sdf.format(selectedDateDariTanggal);
    String formattedDateSampaiTanggal = sdf.format(selectedDateSampaiTanggal);
        try {
    Connection koneksi = Basisdata.getConnection();
    String id_karyawan = idKaryawanComboBox.getSelectedItem().toString();
    String jabatan = jabatanTextField.getText();


    
        String updateSQL = "UPDATE jabatan SET " +
            "jabatan = ?, " +
            "dari_tanggal = ?, " +
            "sampai_tanggal = ? " +
            "WHERE id_karyawan = ?";
        PreparedStatement updateStatement = koneksi.prepareStatement(updateSQL);
        updateStatement.setString(1, jabatan);
        updateStatement.setString(2, formattedDateDariTanggal);
        updateStatement.setString(3, formattedDateSampaiTanggal);
        updateStatement.setInt(4, Integer.parseInt(id_karyawan));
        updateStatement.executeUpdate();


    koneksi.close();
    dispose();
} catch (SQLException ex) {
    System.err.println(ex.getMessage());
}
    
    }//GEN-LAST:event_ubahButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JabatanAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JabatanAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JabatanAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JabatanAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JabatanAddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private org.jdesktop.swingx.JXDatePicker dariTanggalDatePicker;
    private javax.swing.JComboBox<String> idKaryawanComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jabatanTextField;
    private javax.swing.JLabel judulLabel;
    private org.jdesktop.swingx.JXDatePicker sampaiTanggalDatePicker;
    private javax.swing.JButton simpanButton;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables
}
