/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.mycompany.manajemenkaryawan.db.frames.karyawan.KaryawanViewFrame;
import com.mycompany.manajemenkaryawan.db.frames.jabatan.JabatanViewFrame;
import com.mycompany.manajemenkaryawan.db.frames.gaji.GajiViewFrame;
import com.mycompany.manajemenkaryawan.db.frames.departemen.DepartemenViewFrame;
import com.mycompany.manajemenkaryawan.db.frames.departemenkaryawan.DepartemenKaryawanViewFrame;
import com.mycompany.manajemenkaryawan.db.frames.departemenmanajer.DepartemenManajerViewFrame;


/**
 *
 * @author USER
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        karyawanButton = new javax.swing.JButton();
        jabatanButton = new javax.swing.JButton();
        gajiButton = new javax.swing.JButton();
        departemenButton = new javax.swing.JButton();
        departemenKaryawanButton = new javax.swing.JButton();
        departemenManajerButton = new javax.swing.JButton();
        tutupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Menu Utama");

        karyawanButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        karyawanButton.setForeground(new java.awt.Color(0, 0, 153));
        karyawanButton.setText("Data Karyawan");
        karyawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanButtonActionPerformed(evt);
            }
        });

        jabatanButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jabatanButton.setForeground(new java.awt.Color(0, 0, 153));
        jabatanButton.setText("Data Jabatan");
        jabatanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanButtonActionPerformed(evt);
            }
        });

        gajiButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        gajiButton.setForeground(new java.awt.Color(0, 0, 153));
        gajiButton.setText("Data Gaji");
        gajiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiButtonActionPerformed(evt);
            }
        });

        departemenButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        departemenButton.setForeground(new java.awt.Color(0, 0, 153));
        departemenButton.setText("Data Departemen");
        departemenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departemenButtonActionPerformed(evt);
            }
        });

        departemenKaryawanButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        departemenKaryawanButton.setForeground(new java.awt.Color(0, 0, 153));
        departemenKaryawanButton.setText("Data Departemen Karyawan");
        departemenKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departemenKaryawanButtonActionPerformed(evt);
            }
        });

        departemenManajerButton.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        departemenManajerButton.setForeground(new java.awt.Color(0, 0, 153));
        departemenManajerButton.setText("Data Departemen Manajer");
        departemenManajerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departemenManajerButtonActionPerformed(evt);
            }
        });

        tutupButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tutupButton.setForeground(new java.awt.Color(0, 0, 153));
        tutupButton.setText("Tutup");
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(departemenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(karyawanButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jabatanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departemenKaryawanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departemenManajerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gajiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tutupButton)
                .addGap(430, 430, 430))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(karyawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jabatanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gajiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departemenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departemenKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departemenManajerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(tutupButton)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gajiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiButtonActionPerformed
        GajiViewFrame f = new GajiViewFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gajiButtonActionPerformed

    private void departemenKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departemenKaryawanButtonActionPerformed
        DepartemenKaryawanViewFrame f = new DepartemenKaryawanViewFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_departemenKaryawanButtonActionPerformed

    private void departemenManajerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departemenManajerButtonActionPerformed
        DepartemenManajerViewFrame f = new DepartemenManajerViewFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_departemenManajerButtonActionPerformed

    private void karyawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanButtonActionPerformed
        KaryawanViewFrame f = new KaryawanViewFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_karyawanButtonActionPerformed

    private void jabatanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanButtonActionPerformed
        JabatanViewFrame f = new JabatanViewFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jabatanButtonActionPerformed

    private void departemenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departemenButtonActionPerformed
        DepartemenViewFrame f = new DepartemenViewFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_departemenButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed
        dispose();
    }//GEN-LAST:event_tutupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton departemenButton;
    private javax.swing.JButton departemenKaryawanButton;
    private javax.swing.JButton departemenManajerButton;
    private javax.swing.JButton gajiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jabatanButton;
    private javax.swing.JButton karyawanButton;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables
}
