package com.mycompany.manajemenkaryawan.db.frames.gaji;

import com.mycompany.manajemenkaryawan.db.Basisdata;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class GajiAddFrame extends javax.swing.JFrame {

    /**
     * Creates new form GajiAddFrame
     */
    public GajiAddFrame() {
        initComponents();
        ubahButton.setEnabled(false);
        try {
            Connection koneksi = Basisdata.getConnection();
            String findSQL = "SELECT id_karyawan FROM karyawan";
            Statement statement = koneksi.createStatement();
            ResultSet resultSet = statement.executeQuery(findSQL);
            while(resultSet.next()){
                idKaryawanComboBox.addItem(Integer.toString(resultSet.getInt("id_karyawan")));
            }
            koneksi.close();
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
         
    }
    public GajiAddFrame(int id_karyawan) {
        initComponents();
        simpanButton.setEnabled(false);
        try {
    Connection koneksi = Basisdata.getConnection();
    String findSQL = "SELECT * FROM gaji WHERE id_karyawan=?";
    PreparedStatement preparedStatement = koneksi.prepareStatement(findSQL);
    preparedStatement.setInt(1, id_karyawan);
    ResultSet resultSet = preparedStatement.executeQuery();
    while(resultSet.next()){
        idKaryawanComboBox.addItem(Integer.toString(resultSet.getInt("id_karyawan")));
        gajiTextField.setText(resultSet.getString("gaji"));
        dariTanggalDatePicker.setDate(resultSet.getDate("dari_tanggal"));
        sampaiTanggalDatePicker.setDate(resultSet.getDate("sampai_tanggal"));
    }
    koneksi.close();
} catch (SQLException ex) {
    System.err.println(ex.getMessage());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gajiTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        dariTanggalDatePicker = new org.jdesktop.swingx.JXDatePicker();
        sampaiTanggalDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idKaryawanComboBox = new javax.swing.JComboBox<>();
        ubahButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judulLabel.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(0, 153, 0));
        judulLabel.setText("Tambah Data Gaji");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("ID Karyawan");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Gaji");

        gajiTextField.setBackground(new java.awt.Color(204, 255, 204));

        simpanButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        simpanButton.setForeground(new java.awt.Color(0, 153, 51));
        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        batalButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        batalButton.setForeground(new java.awt.Color(0, 153, 51));
        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        dariTanggalDatePicker.setBackground(new java.awt.Color(204, 255, 204));

        sampaiTanggalDatePicker.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Dari Tanggal");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Sampai Tanggal");

        idKaryawanComboBox.setBackground(new java.awt.Color(204, 255, 204));

        ubahButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ubahButton.setForeground(new java.awt.Color(0, 153, 51));
        ubahButton.setText("Ubah");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sampaiTanggalDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dariTanggalDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gajiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(idKaryawanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(batalButton)
                        .addGap(174, 174, 174))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ubahButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(judulLabel)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judulLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idKaryawanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gajiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dariTanggalDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sampaiTanggalDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahButton)
                    .addComponent(simpanButton))
                .addGap(45, 45, 45)
                .addComponent(batalButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        Date selectedDateDariTanggal = dariTanggalDatePicker.getDate();
        Date selectedDateSampaiTanggal = sampaiTanggalDatePicker.getDate();
        if (gajiTextField.getText().equals("") || selectedDateDariTanggal == null || selectedDateSampaiTanggal == null) {
    JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
    return;
}
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDateDariTanggal = sdf1.format(selectedDateDariTanggal);
        SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDateSampaiTanggal = sdf2.format(selectedDateSampaiTanggal);
        try {
    Connection koneksi = Basisdata.getConnection();
    String id_karyawan = idKaryawanComboBox.getSelectedItem().toString();
    String gaji = gajiTextField.getText();

    String checkSQL = "SELECT * FROM gaji WHERE id_karyawan=?";
    PreparedStatement checkStatement = koneksi.prepareStatement(checkSQL);
    checkStatement.setInt(1, Integer.parseInt(id_karyawan));
    ResultSet checkResult = checkStatement.executeQuery();

    if (checkResult.next()) {
        JOptionPane.showMessageDialog(null, "Data Sudah Ada");
    } else {
        // Lakukan operasi insert
        String insertSQL = "INSERT INTO gaji (id_karyawan, gaji, dari_tanggal, sampai_tanggal) VALUES (?, ?, ?, ?)";
        PreparedStatement insertStatement = koneksi.prepareStatement(insertSQL);
        insertStatement.setInt(1, Integer.parseInt(id_karyawan));
        insertStatement.setString(2, gaji);
        insertStatement.setString(3, formattedDateDariTanggal);
        insertStatement.setString(4, formattedDateSampaiTanggal);
        insertStatement.executeUpdate();
        koneksi.close();
        dispose();
    }

    
} catch (SQLException ex) {
    System.err.println(ex.getMessage());
}
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        dispose();
    }//GEN-LAST:event_batalButtonActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        Date selectedDateDariTanggal = dariTanggalDatePicker.getDate();
        Date selectedDateSampaiTanggal = sampaiTanggalDatePicker.getDate();
        if (gajiTextField.getText().equals("") || selectedDateDariTanggal == null || selectedDateSampaiTanggal == null) {
    JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
    return;
}
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDateDariTanggal = sdf1.format(selectedDateDariTanggal);
        SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDateSampaiTanggal = sdf2.format(selectedDateSampaiTanggal);
         try {
    Connection koneksi = Basisdata.getConnection();
String id_karyawan = idKaryawanComboBox.getSelectedItem().toString();
String gaji = gajiTextField.getText();


               
String updateSQL = "UPDATE gaji SET " +
"gaji = '" + gaji + "'," +
"dari_tanggal = '" + formattedDateDariTanggal + "'," +
"sampai_tanggal = '" + formattedDateSampaiTanggal + "'" +
"WHERE id_karyawan =" + id_karyawan;
    Statement updateStatement = koneksi.createStatement();
    updateStatement.executeUpdate(updateSQL);


koneksi.close();
dispose();
} catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_ubahButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiAddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private org.jdesktop.swingx.JXDatePicker dariTanggalDatePicker;
    private javax.swing.JTextField gajiTextField;
    private javax.swing.JComboBox<String> idKaryawanComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel judulLabel;
    private org.jdesktop.swingx.JXDatePicker sampaiTanggalDatePicker;
    private javax.swing.JButton simpanButton;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables
}
